### PR TITLE
Revert "add manifest and service worker"

### PR DESCRIPTION
**Pull request by muzam1l**
Reverts muzam1l/mcalculator#1

It is not complete as its having some issues like

- Offline mode doesn't work on mobile browsers
- There is no prompt to install it as offline native webapp both in desktop and mobile

@NWylynko i created the new branch offline-app to work on these issues and complete offline experience there.

### CODE REVIEW

**Comment by NWylynko** [comment]
It needs to be hosted with https for those options to show up in the browser. If you've done that and it's still not working idk.

**Comment by muzam1l** [comment]
Right, heroku doesn't do automatic http to https on free plan. So vl have to see other option for that.

**Comment by muzam1l** [comment]
Plus icons doesn't seen to show either, [hosted here](http://mcalc-test.herokuapp.com)

**Comment by NWylynko** [comment]
Screenshot_20200419-180751
Screenshot_20200419-180816
Screenshot_20200419-180821


http://mcalc-test.herokuapp.com/ works fine on my phone.
the icon isnt showing up because thats looking for a favicon which needs to be defined in the html and needs to be generated from the master image.

**Comment by muzam1l** [comment]
Thats Good, i also installed it on desktop, and now behaves like native app when installed from chrome (windows ver 2004). So we just need to host it on https only.
calc-native-app
But there seems to be problem with Edge (new one). Once installed from this it is not available offline system wide and only available through edge (say cannot search like chrome  one) and even other apps through edge behave normally (so not problem with how edge works), Little issue but needs to keep in mind.
edge-app-menu

**Comment by NWylynko** [comment]
i believe `if ('serviceWorker' in navigator) {` is only true if the page is served over https. i have personally used heroku but it seems it doesnt automatically redirect http to https so need to make sure your on https for the service worker to cache the files.

**Comment by NWylynko** [comment]
yup just tested it, went to the https version on edge, installed it, closed it and turned off my wifi then opened the app and it loaded perfectly

**Comment by muzam1l** [comment]
@NWylynko , can you make fresh pull pull request to this branch then  (master), merging offline-app into this doesn't seem to work.
Along with maybe favicon icon.
sorry for the overhead.

**Pull request merged**
